{
    "Home":"Home",
    "Blog":"Blog",
    "Contact":"Contact",
    "All":"All",
    "Name":"Name",
    "Username":"Username",
    "Email_Address":"Email Address",
    "Subject":"Subject",
    "Message":"Message",
    "Send_Message":"Send Message",
    "Categories":"Categories",
    "by":"by",
    "Search_your_keyword":"Search your keyword",
    "year":"year",
    "Submit":"Submit",
    "Testimonial":"Testimonial",
    "Contact_Us":"Contact Us",
    "FAQ":"FAQ",
    "Share":"Share",
    "Latest_Blog":"Latest Blog",
    "Category":"Category",
    "Enter_Email_Address":"Enter Email Address",
    "Enter_Name":"Enter Name",
    "Only_zip_file_is_allowed":"Only zip file is allowed",
    "find_your_dream_course":"Find Your Dream Course",
    "search_course_here":"Search Course Here",
    "select_category":"Select a Category",
    "find_course":"Find Course",
    "no_course_category_found":"No Course Category Found !",
    "no_featured_course_found":"No Featured Course Found !",
    "no_course_found":"No Course Found !",
    "free":"Free",
    "price":"Price",
    "students":"Students",
    "no_feature_found":"No Feature Found!",
    "no_information_found":"No Information Found !",
    "no_testimonial_found":"No Testimonial Found !",
    "no_featured_instructor_found":"No Featured Instructor Found !",
    "no_instructor_found":"No Instructor Found !",
    "no_blog_found":"No Blog Found !",
    "frequently_asked_questions":"Frequently Asked Questions",
    "no_faq_found":"No FAQ Found !",
    "please_login_to_give_your_feedback":"Please login to give your feedback.",
    "ratings":"Ratings",
    "enter_your_feedback":"Enter Your Feedback",
    "this_course_is_not_reviewed_yet":"This course is not reviewedyet",
    "discounted_price":"Discounted Price",
    "you_have_already_enrolled_in_this_course":"You have already enrolled inthis course",
    "select_payment_gateway":"Select Payment Gateway",
    "enter_your_card_number":"Enter Your Card Number",
    "enter_CVC_number":"Enter CVC Number",
    "enter_expiry_month":"Enter Expiry Month",
    "enter_expiry_year":"Enter Expiry Year",
    "enter_card_code":"Enter Card Code",
    "description":"Description",
    "instructions":"Instructions",
    "attachment":"Attachment *",
    "enter_your_coupon":"Enter Your Coupon",
    "apply":"Apply",
    "enrol_now":"Enrol Now",
    "this_course_includes":"This Course Includes",
    "related_courses":"Related Courses",
    "here":"here.",
    "sort_by":"Sort By",
    "new_course":"New Course",
    "old_course":"Old Course",
    "ascending":"Ascending",
    "descending":"Descending",
    "search_course":"Search Course",
    "course_type":"Course Type",
    "all_courses":"All Courses",
    "free_courses":"Free Courses",
    "premium_courses":"Premium Courses",
    "all_category":"All Category",
    "filter_by_price":"Filter By Price",
    "phone_number":"Phone Number",
    "email_address":"Email Address",
    "location":"Location",
    "get_in_touch":"Get In Touch",
    "enter_your_full_name":"Enter Your Full Name",
    "enter_your_email":"Enter Your Email",
    "enter_email_subject":"Enter Email Subject",
    "write_your_message":"Write Your Message",
    "send":"Send",
    "information_of":"Information of",
    "follow_me":"Follow Me",
    "close":"Close",
    "login":"Login",
    "signup":"Signup",
    "logout":"Logout",
    "search_your_keyword":"Search Your keyword",
    "useful_links":"Useful Links",
    "no_link_found":"No Link Found !",
    "related_blog":"Related Blog",
    "no_related_blog_found":"No Related Blog Found !",
    "search_blog":"Search Blog",
    "search_by_title":"Search By Title",
    "no_category_found":"No Category Found",
    "success":"Success",
    "your_transaction_was_successful":"Your transaction was successful",
    "We_have_sent_you_a_mail_with_an_invoice":"We have sent you a mail with an invoice",
    "thank_you":"Thank you",
    "course":"Course",
    "duration":"Duration",
    "action":"Action",
    "my_courses":"My Courses",
    "Purchase_History":"Purchase History",
    "edit_profile":"Edit Profile",
    "edit_your_profile":"Edit Your Profile",
    "upload":"Upload",
    "first_name":"First Name",
    "last_name":"Last Name",
    "email":"Email",
    "contact_number":"Contact Number",
    "phone":"Phone",
    "address":"Address",
    "city":"City",
    "state":"State",
    "country":"Country",
    "submit":"Submit",
    "dashboard":"Dashboard",
    "account_information":"Account Information",
    "curriculum":"Curriculum",
    "back":"Back",
    "certificate":"Certificate",
    "you_scored":"You scored",
    "retake_quiz":"Retake Quiz",
    "check":"Check",
    "next":"Next",
    "quiz":"Quiz",
    "download":"Download",
    "print":"Print",
    "current_password":"Current Password",
    "reset_password":"Reset Password",
    "new_password":"New Password",
    "confirm_new_password":"Confirm New Password",
    "change_password":"Change Password",
    "confirm_password":"Confirm Password",
    "payment_success":"Payment Success",
    "password":"Password",
    "proceed":"Proceed",
    "lost_your_password":"Lost your password",
    "custom_page":"Custom Page",
    "Courses":"Courses",
    "Instructors":"Instructors",
    "reviews":"Reviews",
    "no_featured_course_category_found":"No Featured Course Category Found",
    "My_Courses":"My Courses",
    "404_page_not_found":"404 page not found",
    "oops_looks_like_you_are_lost_in_ocean":"Oops! Looks Like You Are Lost in Ocean",
    "get_back_to_home":"Get Back to Home",
    "Subscribe":"Subscribe",
    "Students_Enrolled":"Students Enrolled",
    "Order_ID":"Order ID",
    "Date":"Date",
    "Paid_via":"Paid via",
    "Payment_Status":"Payment Status",
    "Invoice":"Invoice",
    "Completed":"Completed",
    "Pending":"Pending",
    "Rejected":"Rejected",
    "Show":"Show",
    "tenant_offline_payment_success_text":"Your Order Successfully Completed !",
    "play_video":"Play Video",
    "courses":"courses",
    "see_all_course" :"See All Course",
    "enroll_now":"Enroll Now",
    "lessons":"Lessons",
    "lesson":"Lesson",
    "no_lesson":"No Lesson",
    "view_more":"View More",
    "all":"All",
    "Our_latest_courses":"Our Latest Courses",
    "subscribe":"Subscribe",
    "enter_email_here":"Enter Email Here",
    "latest_post":"Latest Post"
 }